### ISSUE TITLE
Links/URLs containing an underscore, should the underscore get escaped?

### ISSUE THREAD

**Issue by michaelwechner** [furstenheim/copy-down#10]
Hi

When my HTML contains a link with an underscore (without anchor element), e.g.

https://en.wikipedia.org/wiki/Self-sovereign_identity

then the underscore gets escaped with a backslash, e.g.

https://en.wikipedia.org/wiki/Self-sovereign\_identity

which breaks the link :-(

I guess this is a bug, or do I misunderstand something?

Thanks!

**Comment by furstenheim** [comment]
Hi, this looks like a bug. Could you search for what the markdown
documentation says about this?

Cheers

**Comment by michaelwechner** [comment]
So far I could not find a clear spec description

https://www.markdownguide.org/basic-syntax/#links

but maybe it is not a bug of the converter, but rather a bug of the interpreter (e.g. how Discord is handling the markdown)

- https://github.com/jekyll/jekyll/issues/529
- https://support.discord.com/hc/en-us/community/posts/360043014671-Underscores-being-used-for-formatting-markdown-is-causing-some-text-issues

I will try to dig deeper :-)

**Comment by michaelwechner** [comment]
I did some more testing and following works fine with Slack and Discord

`<a href="https://en.wikipedia.org/wiki/Self-sovereign_identity">Self-Sovereign Identity from Wikipedia</a>`

but the following cases I have trouble with at Discord and Slack

`<a href="https://en.wikipedia.org/wiki/Self-sovereign_identity">https://en.wikipedia.org/wiki/Self-sovereign_identity</a>`
and
`https://en.wikipedia.org/wiki/Self-sovereign_identity`

because the underscore gets escaped with a backslash when converting https://en.wikipedia.org/wiki/Self-sovereign\_identity

and then Slack complains about invalid JSON and Discord is not able to display properly respectively the link is broken.

I will try to implement some workaround for this edge case :-)

**Comment by furstenheim** [comment]
Haha, can't see the difference, can you add it as code snippet?

**Comment by michaelwechner** [comment]
yes, sorry, just did now :-)

**Comment by michaelwechner** [comment]
Both, Discord and Slack work fine, if I send the URL with underscore unescaped

`https://en.wikipedia.org/wiki/Self-sovereign_identity`

It came to my mind, that maybe one could make the escaping of underscores inside a URL configurable, WDYT?

For text which is not a URL/Link, the escaping makes sense, for example TEST\_UNDERSCORE gets displayed properly by Discord as TEST_UNDERSCORE

**Comment by furstenheim** [comment]
Hi,
I've tried escaping the `_` in intellij and Github. Both of them accept it. So if there is really an issue in Discord I would suggest that you open a ticket to them.

BTW, your comment here "Slack complains about invalid JSON" makes me think that in your application you are not writing a JSON properly. Can it be that you are just building the JSON yourself instead of using a serializer? Something like `"\"payload\":" + resultFromCopyDown`. That is deemed to fail. JSON is completely capable of representing any string, including a `\_`

Cheers

**Comment by michaelwechner** [comment]
> Hi, I've tried escaping the `_` in intellij and Github.

thanks for testing!


 > Both of them accept it. So if there is really an issue in Discord I would suggest that you open a ticket to them.

sure, will do this


> BTW, your comment here "Slack complains about invalid JSON" makes me think that in your application you are not writing a JSON properly. Can it be that you are just building the JSON yourself instead of using a serializer? Something like `"\"payload\":" + resultFromCopyDown`. That is deemed to fail. JSON is completely capable of representing any string, including a `\_`

no, I do not just copy "resultFromCopyDown", but there was a bug otherwise, which I fixed in the meantime.
Everything works fine, except URLs with underscore, but yes, let me double-check the serializing.

Thanks
