### ISSUE TITLE
UL and OL list conversions fail with AdoptOpen JDK

### ISSUE THREAD

**Issue by mandragorn** [furstenheim/copy-down#2]
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200122_511 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)
```
<dependency>
  <groupId>io.github.furstenheim</groupId>
  <artifactId>copy_down</artifactId>
  <version>1.0</version>
</dependency>
```
String to convert:
```
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
```

Result:
```
Coffee

Tea

Milk
```

**Comment by furstenheim** [comment]
The following:

```
    @Test
    public void someTest () {
            String html = "<ol>\n" +
                          "  <li>Coffee</li>\n" +
                          "  <li>Tea</li>\n" +
                          "  <li>Milk</li>\n" +
                          "</ol>";

            CopyDown copyDown = new CopyDown();
            String markdown = copyDown.convert(html);
            System.out.println("-----------");
            System.out.println(markdown);
            System.out.println("-----------");
    }
```

Prints:

    -----------
    1.  Coffee
    2.  Tea
    3.  Milk
    -----------

The library requires `org.jsoup:jsoup:1.13.1`, do you happen to have jsoup in your dependency tree in another version?

**Comment by mandragorn** [comment]
The only references to jsoup is here:
```
[INFO] --- maven-dependency-plugin:2.4:tree (default-cli) @ survey-api-common ---
...
[INFO] +- io.github.furstenheim:copy_down:jar:1.0:compile
[INFO] |  \- org.jsoup:jsoup:jar:1.13.1:compile
```

Curious thing is that it works for us in some cases but not in others.

These work:
1. Maven unit tests with java setup to use oracle java.
2. Running unit tests inside intellij in debug mode pointed at adoptopen jdk

These do not work:
1. Maven unit tests with java setup to use adoptopen jdk.
2. Running unit tests inside intellij in normal run mode pointed at adoptopen jdk

I would provide more debugging info but it is successful when run inside intellij using debug mode.  Unfortunately it is breaking unit tests on our automated test servers so we can't use the library and we aren't confident that it will work once we fully integrate it into our production code.

At this point we had to move on to another library (https://github.com/vsch/flexmark-java) to keep our internal project moving.

**Comment by furstenheim** [comment]
I've executed the test with liberica-1.8.0_242, corretto-11.0.6 and openjdk-14, they all parse the the list correctly in the tests.

Feel free to create a cr or reopen if you find the culprit.

**Comment by mandragorn** [comment]
Sounds good. 

We are using openjdk build 1.8.0_242-b08.
