### ISSUE TITLE
Expose addRule?

### ISSUE THREAD

**Issue by kevinkaishao** [furstenheim/copy-down#6]
Hi, just wondering why `addRule` is made private? It's available in Turndown as part of the API, and I have a use case where I need to add some custom rules. If you don't have any strong opinions on making it public, I can raise a PR to expose it.

**Comment by furstenheim** [comment]
Hi @kevinkaishao, I think it makes sense to make it public. It might need a bit of refactoring, just adding a rule with the current code it would add it after the default rule and do nothing. Feel free to open a pr
